### ISSUE TITLE
Make a guide on how to add roms

### ISSUE THREAD

**Issue by theblobscp** [ayvacs/gba.js.org#10]
I have a few roms of my own that I would like to run that aren't on the current list. I don't know if you would accept them and add them on to this project, so I wanted a guide so I can add it to my own fork.

**Comment by ayvacs** [comment]
I can work on making a guide later, but here's a quick tutorial - let me know if it works:

* Fork the repo to your machine
* Add the .gba file to the "binaries" folder and make sure the file name doesn't have a space in it
* Register the game by adding the game to the `games` variable in `modules/CoreGlueCode.js`. The line that you add should look like: `"gba_file_name": "Game Name"` (`gba_file_name` should not include the file extension)
* Host the repo to a live server. (if you use VSCode you can use the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension)
* Open the server in your web browser and go to `/player#gba_file_name` (`gba_file_name` should not include the file extension)

For example if you were adding Advance Wars and the file name was `advancewars.gba` the line you added to the `games` variable would look like: `"advancewars": "Advance Wars"` and you would open `/player#advancewars`

I don't really know how to properly explain it, so if you don't understand I can make a video tutorial for you. :)

And by the way I'm always open to adding new games to this repo!

**Comment by theblobscp** [comment]
Well to be honest, I’m kinda lazy. I did try to get it to run though. It didn’t work, but I tried.

**Comment by ayvacs** [comment]
I can help you out, which part didn't work?

**Comment by theblobscp** [comment]
Yeah my bad, I ended up finding another solution to this. Thanks though.
