### ISSUE TITLE
Mobile on-screen buttons don't work

### ISSUE THREAD

**Issue by rjd1922** [ayvacs/gba.js.org#20]
I can't play this on Android Chrome as the on-screen buttons do nothing.

**Comment by slimhappy** [comment]
You may add this to GUIGlueCode.js


    addEvent("touchstart", document.getElementById("touch-a"), function () {
        IodineGUI.Iodine.keyDown(0);
    });
    addEvent("touchend", document.getElementById("touch-a"), function () {
        IodineGUI.Iodine.keyUp(0);
    });
    addEvent("touchstart", document.getElementById("touch-b"), function () {
        IodineGUI.Iodine.keyDown(1);
    });
    addEvent("touchend", document.getElementById("touch-b"), function () {
        IodineGUI.Iodine.keyUp(1);
    });
    addEvent("touchstart", document.getElementById("touch-select"), function () {
        IodineGUI.Iodine.keyDown(2);
    });
    addEvent("touchend", document.getElementById("touch-select"), function () {
        IodineGUI.Iodine.keyUp(2);
    });
    addEvent("touchstart", document.getElementById("touch-start"), function () {
        IodineGUI.Iodine.keyDown(3);
    });
    addEvent("touchend", document.getElementById("touch-start"), function () {
        IodineGUI.Iodine.keyUp(3);
    });
    addEvent("touchstart", document.getElementById("touch-right"), function () {
        IodineGUI.Iodine.keyDown(4);
    });
    addEvent("touchend", document.getElementById("touch-right"), function () {
        IodineGUI.Iodine.keyUp(4);
    });
    addEvent("touchstart", document.getElementById("touch-left"), function () {
        IodineGUI.Iodine.keyDown(5);
    });
    addEvent("touchend", document.getElementById("touch-left"), function () {
        IodineGUI.Iodine.keyUp(5);
    });
    addEvent("touchstart", document.getElementById("touch-up"), function () {
        IodineGUI.Iodine.keyDown(6);
    });
    addEvent("touchend", document.getElementById("touch-up"), function () {
        IodineGUI.Iodine.keyUp(6);
    });
    addEvent("touchstart", document.getElementById("touch-down"), function () {
        IodineGUI.Iodine.keyDown(7);
    });
    addEvent("touchend", document.getElementById("touch-down"), function () {
        IodineGUI.Iodine.keyUp(7);
    });
    addEvent("touchstart", document.getElementById("touch-r"), function () {
        IodineGUI.Iodine.keyDown(8);
    });
    addEvent("touchend", document.getElementById("touch-r"), function () {
        IodineGUI.Iodine.keyUp(8);
    });
    addEvent("touchstart", document.getElementById("touch-l"), function () {
        IodineGUI.Iodine.keyDown(9);
    });
    addEvent("touchend", document.getElementById("touch-l"), function () {
        IodineGUI.Iodine.keyUp(9);
    });

**Comment by rjd1922** [comment]
Does it matter where in the code that's added? Could you add it and submit a pull request?

**Comment by ayvacs** [comment]
fixed
