### ISSUE TITLE
just a Question of interest

### ISSUE THREAD

**Issue by copakahuna** [ayvacs/gba.js.org#22]
Regarding the Audio FIFO
In the push8 function;
why would you push the sample 4 times into the fifo? :)
wouldnt one want to fill the rest of the 32bit with leading zeroes (if the fifo is read in 32bit chunks)?
From my understanding, the audioplayer would play/repeat the sample 4 times which should probably end in some weird sound.

What am i not getting here? 

I would really appreciate an answer

function i'm reffering to:
GameBoyAdvanceFIFO.prototype.push8 = function (sample) {
    sample = sample | 0;
    this.push(sample | 0);
    this.push(sample | 0);
    this.push(sample | 0);
    this.push(sample | 0);
}

**Comment by copakahuna** [comment]
* play/repeat the sample 4 times OR interpret the sample as a 32bit number which would lead to a completely different shound?

**Comment by ayvacs** [comment]
I genuinely have no clue, I'm awful at JS coding. feel free to make a PR if you want to improve the code :)
