### ISSUE TITLE
Publish .htaccess / nginx rules

### ISSUE THREAD

**Issue by TCB13** [ayvacs/gba.js.org#24]
Hey,

A simple request, publish the `.htaccess` / nginx rules needed to self-host this properly.

Thank you.

**Comment by ayvacs** [comment]
I'm not sure what you mean, the site is published on github pages

**Comment by TCB13** [comment]
So, from what I can see if anyone wants to host this on a standard nginx / apache webserver it needs to be configured to rewrite all paths to `index.html`. Is that right?

**Comment by ayvacs** [comment]
yeah it already does that automatically
![image](https://github.com/ayvacs/gba.js.org/assets/74518502/98d085dd-9614-4c3c-8de2-e0d17d4bb84e)

**Comment by TCB13** [comment]
> yeah it already does that automatically ![image](https://user-images.githubusercontent.com/74518502/264158451-98d085dd-9614-4c3c-8de2-e0d17d4bb84e.png)

Last time I checked it wasn't working, did you add that code now?

**Comment by ayvacs** [comment]
nah it was added since before you made this issue and it's still working atleast on my end
