### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by hellothere-imyoung** [ayvacs/gba.js.org#42]
I am hosting the source code on cPanel, and the home page loads up perfectly however when I press on a game, I get "404: Not Found The resource requested could not be found on this server!" error. I was hoping that I could get some assistance with this, I tried to watch a YouTube video where they talked about .htaccess files and I tried to implement that into my code but that didn't work either.

As it's pretty obvious, I don't know what I'm doing so pardon the silly question.

The site I'm trying to do this on is https://testsitelol.org

**Comment by ayvacs** [comment]
I am not going to pretend that I know how HTML hosting works, or why this solution works. You will need to change the line of code in index.html at line 224 to be:

`if (document.location.hostname == "testsitelol.org") {`

That code is a hacky fix to a problem that I should probably have come up with a better solution to.

Let me know if it works.

(Alternately, you could remove that entire <script> tag and replace all occurrences of "player#" to "player.html#" in the file.)

**Comment by hellothere-imyoung** [comment]
It worked, thanks so much!

But now I'm receiving another problem lol...
My school chromebook is blocking this site, probably because gba.js.org is blocked. Is there a way to change the appearance of the name so it instead says "online" instead of "GBA Online"? I hope the name change fixes this, if not, no problem.

**Comment by ayvacs** [comment]
Sorry for the late reply,

If the network is blocking gba.js.org then there's nothing we can do to fix it. The school administrator would have to manually unblock the site.

You can try to look through this repo's forks to see if any are actively being hosted on different URLs.

**Comment by ayvacs** [comment]
I pushed a new commit and version (1.4.6) that patches my hacky fix, try updating it and let me know how it goes!
