### ISSUE TITLE
I can open the games

### ISSUE THREAD

**Issue by bennymanjam** [ayvacs/gba.js.org#44]
**Describe the bug:** *A clear and concise description of what the bug is, what you expected to happen, and steps to reproduce the behavior.*
the games won't open and say Your file couldn’t be accessedIt may have been moved, edited, or deleted. ERR_FILE_NOT_FOUND

**Screenshots:** *If applicable, add screenshots to help explain your problem.*
![Screenshot 2024-04-08 9 48 01 AM](https://github.com/ayvacs/gba.js.org/assets/145567240/a689c2c7-aacd-499e-b602-0b91ed993059)

**Device information:** *Information about the device you used to find the bug, including the OS and browser version.*

**Additional context:** *Add any other context about the problem here.*

**Comment by ayvacs** [comment]
Could you send me a screenshot w/ the url bar in view as well as the developer console? https://balsamiq.com/support/faqs/browserconsole/

I have an idea of what might be causing this, I can push a fix later today

**Comment by bennymanjam** [comment]
ok I hope I gave you the right stuff.
![Screenshot 2024-04-08 12 27 06 PM](https://github.com/ayvacs/gba.js.org/assets/145567240/164b090e-693f-418e-97be-0f666233d9e9)
![Screenshot 2024-04-08 12 28 10 PM](https://github.com/ayvacs/gba.js.org/assets/145567240/ee9a7e3e-a64f-4116-82c4-59f66453fa1b)

**Comment by ayvacs** [comment]
You've downloaded the files and you're trying to open them locally, but the repo can only run on a live server

You can look into [this extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) to start a server natively in vs code
