### ISSUE TITLE
Minish cap uses PAL version

### ISSUE THREAD

**Issue by DaBiggestBozo** [ayvacs/gba.js.org#48]
The minish cap built in ROM uses the PAL version of the game, which has several bugs that are not in the US or Japanese versions

**Comment by rjd1922** [comment]
The audio sounds off, too. Should definitely change it to the US version.

**Comment by ayvacs** [comment]
Fixed!

**Comment by rjd1922** [comment]
Sound effects still sound wrong in The Minish Cap.
